### ISSUE TITLE
Why distribute from extras-devel?

### ISSUE THREAD

**Issue by 0xABAB** [agamez/yappari#48]
I would rather not expose myself to unstable software on my production systems (and my phone is a production system ;) )

As such the simple question: are there any plans to upload to the normal repositories? 

```
The software hosted in extras-devel is not ready for normal users!
PLEASE PLEASE PLEASE don't play with it unless you really know what you are doing. Be ready to file proper bug reports instead of posting complaints.
Expected problems: crashes, battery drain, poor system performance, full disk space & more - SERIOUSLY!
Don't play with Extras-devel if you haven't backed up your data or aren't prepared to re-flash your device.
```

**Comment by agamez** [comment]
Because the process to upload packages to the "normal" repositories as you call them begins with uploading to extras-devel, promoting to extras-testing and after enough votes in favour, to extras.

https://wiki.maemo.org/Extras

In any case, you should read this http://talk.maemo.org/showthread.php?t=94465
